# Generated by Django 5.2.7 on 2026-04-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_oauth_degree_and_more'),
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatenote',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Candidate this note is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_notes', to=settings.AUTH_USER_MODEL, verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='candidatenote',
            name='employer',
            field=models.ForeignKey(blank=True, help_text='Employer who wrote this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employerprofile', verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='candidatenote',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Job application this note relates to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='author',
            field=models.ForeignKey(blank=True, help_text='User who wrote the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company being reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='employers.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Job application this interview is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='employers.jobapplication', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(blank=True, help_text='Employer conducting the interview', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employerprofile', verbose_name='Interviewer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company posting this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='employers.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='User applying for the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Job position being applied for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='employers.job', verbose_name='Job'),
        ),
    ]
