# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_remove_candidatenote_note_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatenote',
            name='note_en',
            field=models.TextField(help_text='Content of the note about the candidate', null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='note_ru',
            field=models.TextField(help_text='Content of the note about the candidate', null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='note_uz',
            field=models.TextField(help_text='Content of the note about the candidate', null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(help_text='Brief description of the company and its activities', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_ru',
            field=models.TextField(help_text='Brief description of the company and its activities', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_uz',
            field=models.TextField(help_text='Brief description of the company and its activities', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_en',
            field=models.CharField(help_text='e.g., Tashkent, Uzbekistan', max_length=100, null=True, verbose_name='Headquarters'),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_ru',
            field=models.CharField(help_text='e.g., Tashkent, Uzbekistan', max_length=100, null=True, verbose_name='Headquarters'),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_uz',
            field=models.CharField(help_text='e.g., Tashkent, Uzbekistan', max_length=100, null=True, verbose_name='Headquarters'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(help_text='Official company name', max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ru',
            field=models.CharField(help_text='Official company name', max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_uz',
            field=models.CharField(help_text='Official company name', max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='cons_en',
            field=models.TextField(help_text='Negative aspects of the company', null=True, verbose_name='Cons'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='cons_ru',
            field=models.TextField(help_text='Negative aspects of the company', null=True, verbose_name='Cons'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='cons_uz',
            field=models.TextField(help_text='Negative aspects of the company', null=True, verbose_name='Cons'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='pros_en',
            field=models.TextField(help_text='Positive aspects of the company', null=True, verbose_name='Pros'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='pros_ru',
            field=models.TextField(help_text='Positive aspects of the company', null=True, verbose_name='Pros'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='pros_uz',
            field=models.TextField(help_text='Positive aspects of the company', null=True, verbose_name='Pros'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='review_en',
            field=models.TextField(help_text='Detailed review content', null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='review_ru',
            field=models.TextField(help_text='Detailed review content', null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='review_uz',
            field=models.TextField(help_text='Detailed review content', null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='title_en',
            field=models.CharField(help_text='Review title or headline', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='title_ru',
            field=models.CharField(help_text='Review title or headline', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='title_uz',
            field=models.CharField(help_text='Review title or headline', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='department_en',
            field=models.CharField(help_text='Department or team within the company', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='department_ru',
            field=models.CharField(help_text='Department or team within the company', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='department_uz',
            field=models.CharField(help_text='Department or team within the company', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='position_en',
            field=models.CharField(help_text='Job title or position within the company', max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='position_ru',
            field=models.CharField(help_text='Job title or position within the company', max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='position_uz',
            field=models.CharField(help_text='Job title or position within the company', max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_en',
            field=models.TextField(blank=True, help_text='Interview feedback and evaluation', null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_ru',
            field=models.TextField(blank=True, help_text='Interview feedback and evaluation', null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_uz',
            field=models.TextField(blank=True, help_text='Interview feedback and evaluation', null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='interview',
            name='location_en',
            field=models.TextField(help_text='Interview location or meeting details', null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='interview',
            name='location_ru',
            field=models.TextField(help_text='Interview location or meeting details', null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='interview',
            name='location_uz',
            field=models.TextField(help_text='Interview location or meeting details', null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes_en',
            field=models.TextField(blank=True, help_text='Additional notes about the interview', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes_ru',
            field=models.TextField(blank=True, help_text='Additional notes about the interview', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes_uz',
            field=models.TextField(blank=True, help_text='Additional notes about the interview', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_en',
            field=models.TextField(blank=True, help_text='Benefits and perks offered (optional)', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_ru',
            field=models.TextField(blank=True, help_text='Benefits and perks offered (optional)', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_uz',
            field=models.TextField(blank=True, help_text='Benefits and perks offered (optional)', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(help_text='Detailed description of the job and company', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_ru',
            field=models.TextField(help_text='Detailed description of the job and company', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_uz',
            field=models.TextField(help_text='Detailed description of the job and company', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_en',
            field=models.CharField(help_text='e.g., Tashkent, Samarkand, Remote', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_ru',
            field=models.CharField(help_text='e.g., Tashkent, Samarkand, Remote', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_uz',
            field=models.CharField(help_text='e.g., Tashkent, Samarkand, Remote', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_en',
            field=models.TextField(help_text='Skills, experience, and qualifications required', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_ru',
            field=models.TextField(help_text='Skills, experience, and qualifications required', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_uz',
            field=models.TextField(help_text='Skills, experience, and qualifications required', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_en',
            field=models.TextField(help_text='Key responsibilities and duties', null=True, verbose_name='Responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_ru',
            field=models.TextField(help_text='Key responsibilities and duties', null=True, verbose_name='Responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_uz',
            field=models.TextField(help_text='Key responsibilities and duties', null=True, verbose_name='Responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_en',
            field=models.TextField(help_text='Skills required for this position', null=True, verbose_name='Required Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_ru',
            field=models.TextField(help_text='Skills required for this position', null=True, verbose_name='Required Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_uz',
            field=models.TextField(help_text='Skills required for this position', null=True, verbose_name='Required Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(help_text='Position title for this job posting', max_length=200, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_ru',
            field=models.CharField(help_text='Position title for this job posting', max_length=200, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_uz',
            field=models.CharField(help_text='Position title for this job posting', max_length=200, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_en',
            field=models.TextField(help_text="Candidate's cover letter or motivation", null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_ru',
            field=models.TextField(help_text="Candidate's cover letter or motivation", null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_uz',
            field=models.TextField(help_text="Candidate's cover letter or motivation", null=True, verbose_name='Cover Letter'),
        ),
    ]
