# Generated by Django 5.2.7 on 2025-11-28 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event category', max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', verbose_name='Description')),
                ('color', models.CharField(default='#007cba', help_text='Hex color code for UI display', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for UI display', max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=200, verbose_name='Event Title')),
                ('description', models.TextField(help_text='Detailed description of the event', verbose_name='Description')),
                ('short_description', models.TextField(help_text='Brief summary of the event', max_length=300, verbose_name='Short Description')),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('networking', 'Networking'), ('career_fair', 'Career Fair'), ('hackathon', 'Hackathon'), ('webinar', 'Webinar'), ('social', 'Social Event'), ('training', 'Training'), ('other', 'Other')], help_text='Type of event', max_length=20, verbose_name='Event Type')),
                ('start_date', models.DateTimeField(help_text='Event start date and time', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='Event end date and time', verbose_name='End Date')),
                ('location', models.CharField(help_text='General location of the event', max_length=200, verbose_name='Location')),
                ('banner_image', models.ImageField(blank=True, help_text='Main banner image for the event', null=True, upload_to='event_banners/', verbose_name='Banner Image')),
                ('thumbnail', models.ImageField(blank=True, help_text='Small thumbnail image', null=True, upload_to='event_thumbnails/', verbose_name='Thumbnail')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', help_text='Current status of the event', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this event prominently', verbose_name='Featured Event')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True, verbose_name='Slug')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, verbose_name='Tags')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times the event was viewed', verbose_name='Views Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(help_text='Event category for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The photo file', upload_to='event_photos/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was uploaded', verbose_name='Uploaded At')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display this photo', verbose_name='Display Order')),
                ('event', models.ForeignKey(help_text='The event this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event', verbose_name='Event')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this photo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
