# Generated by Django 5.2.7 on 2026-05-11 06:09

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event category', max_length=100, verbose_name='Category Name')),
                ('name_uz', models.CharField(help_text='Name of the event category', max_length=100, null=True, verbose_name='Category Name')),
                ('name_ru', models.CharField(help_text='Name of the event category', max_length=100, null=True, verbose_name='Category Name')),
                ('name_en', models.CharField(help_text='Name of the event category', max_length=100, null=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description')),
                ('color', models.CharField(default='#007cba', help_text='Hex color code for UI display', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for UI display', max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventEmployerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Employer business category name, for example Bank', max_length=150, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Event Employer Category',
                'verbose_name_plural': 'Event Employer Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=200, verbose_name='Event Title')),
                ('title_uz', models.CharField(help_text='Title of the event', max_length=200, null=True, verbose_name='Event Title')),
                ('title_ru', models.CharField(help_text='Title of the event', max_length=200, null=True, verbose_name='Event Title')),
                ('title_en', models.CharField(help_text='Title of the event', max_length=200, null=True, verbose_name='Event Title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('short_description', models.TextField(help_text='Brief summary of the event', max_length=300, verbose_name='Short Description')),
                ('short_description_uz', models.TextField(help_text='Brief summary of the event', max_length=300, null=True, verbose_name='Short Description')),
                ('short_description_ru', models.TextField(help_text='Brief summary of the event', max_length=300, null=True, verbose_name='Short Description')),
                ('short_description_en', models.TextField(help_text='Brief summary of the event', max_length=300, null=True, verbose_name='Short Description')),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('networking', 'Networking'), ('career_fair', 'Career Fair'), ('hackathon', 'Hackathon'), ('webinar', 'Webinar'), ('social', 'Social Event'), ('training', 'Training'), ('other', 'Other')], help_text='Type of event', max_length=20, verbose_name='Event Type')),
                ('start_date', models.DateTimeField(help_text='Event start date and time', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='Event end date and time', verbose_name='End Date')),
                ('location', models.CharField(help_text='General location of the event', max_length=200, verbose_name='Location')),
                ('location_uz', models.CharField(help_text='General location of the event', max_length=200, null=True, verbose_name='Location')),
                ('location_ru', models.CharField(help_text='General location of the event', max_length=200, null=True, verbose_name='Location')),
                ('location_en', models.CharField(help_text='General location of the event', max_length=200, null=True, verbose_name='Location')),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='Maximum number of participants allowed for this event', verbose_name='Maximum Participants')),
                ('allow_students', models.BooleanField(default=True, help_text='Allow students to register for this event', verbose_name='Allow Students')),
                ('allow_alumni', models.BooleanField(default=True, help_text='Allow alumni to register for this event', verbose_name='Allow Alumni')),
                ('allow_employers', models.BooleanField(default=True, help_text='Allow employers to register for this event', verbose_name='Allow Employers')),
                ('allow_admins', models.BooleanField(default=True, help_text='Allow admin users to register for this event', verbose_name='Allow Admins')),
                ('banner_image', models.ImageField(blank=True, help_text='Main banner image for the event', null=True, upload_to='event_banners/', verbose_name='Banner Image')),
                ('thumbnail', models.ImageField(blank=True, help_text='Small thumbnail image', null=True, upload_to='event_thumbnails/', verbose_name='Thumbnail')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', help_text='Current status of the event', max_length=20, verbose_name='Status')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True, verbose_name='Slug')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, verbose_name='Tags')),
                ('tags_uz', models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, null=True, verbose_name='Tags')),
                ('tags_ru', models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, null=True, verbose_name='Tags')),
                ('tags_en', models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, null=True, verbose_name='Tags')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times the event was viewed', verbose_name='Views Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(help_text='User who created the event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('category', models.ForeignKey(help_text='Event category for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory', verbose_name='Category')),
                ('allowed_employer_categories', models.ManyToManyField(blank=True, help_text='Leave empty to allow employers from all business categories', related_name='events', to='events.eventemployercategory', verbose_name='Allowed Employer Categories')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The photo file', upload_to='event_photos/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, verbose_name='Caption')),
                ('caption_uz', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption')),
                ('caption_ru', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption')),
                ('caption_en', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was uploaded', verbose_name='Uploaded At')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display this photo', verbose_name='Display Order')),
                ('event', models.ForeignKey(blank=True, help_text='The event this photo belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='events.event', verbose_name='Event')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('employer', 'Employer'), ('admin', 'Admin')], help_text='User role at the moment of registration', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=20, verbose_name='Participation Status')),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'Absent')], default='registered', max_length=20, verbose_name='Attendance Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked In At')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Token')),
                ('attendance_code', models.CharField(editable=False, help_text='Unique code used for QR check-in.', max_length=24, unique=True, verbose_name='Attendance Code')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_participations', to=settings.AUTH_USER_MODEL, verbose_name='Checked In By')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event Participation',
                'verbose_name_plural': 'Event Participations',
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_participation_per_user')],
            },
        ),
    ]
