# Generated by Django 5.2.7 on 2025-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_uz',
            field=models.TextField(max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='location_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='location_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='location_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Session Title'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Session Title'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Session Title'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Speaker Name'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Speaker Name'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Speaker Name'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='organization_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='organization_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='organization_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Speaker Title'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Speaker Title'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Speaker Title'),
        ),
    ]
