# Generated by Django 5.2.7 on 2025-11-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='comment_en',
            field=models.TextField(help_text='The comment text', null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='comment_ru',
            field=models.TextField(help_text='The comment text', null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='comment_uz',
            field=models.TextField(help_text='The comment text', null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='caption_en',
            field=models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='caption_ru',
            field=models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='caption_uz',
            field=models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='eventrating',
            name='comment_en',
            field=models.TextField(blank=True, help_text='Optional comment with the rating', null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='eventrating',
            name='comment_ru',
            field=models.TextField(blank=True, help_text='Optional comment with the rating', null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='eventrating',
            name='comment_uz',
            field=models.TextField(blank=True, help_text='Optional comment with the rating', null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='comments_en',
            field=models.TextField(blank=True, help_text='Additional comments from the registrant', null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='comments_ru',
            field=models.TextField(blank=True, help_text='Additional comments from the registrant', null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='comments_uz',
            field=models.TextField(blank=True, help_text='Additional comments from the registrant', null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='dietary_restrictions_en',
            field=models.TextField(blank=True, help_text='Any dietary restrictions for catering', null=True, verbose_name='Dietary Restrictions'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='dietary_restrictions_ru',
            field=models.TextField(blank=True, help_text='Any dietary restrictions for catering', null=True, verbose_name='Dietary Restrictions'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='dietary_restrictions_uz',
            field=models.TextField(blank=True, help_text='Any dietary restrictions for catering', null=True, verbose_name='Dietary Restrictions'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='special_requirements_en',
            field=models.TextField(blank=True, help_text='Any special requirements or accommodations', null=True, verbose_name='Special Requirements'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='special_requirements_ru',
            field=models.TextField(blank=True, help_text='Any special requirements or accommodations', null=True, verbose_name='Special Requirements'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='special_requirements_uz',
            field=models.TextField(blank=True, help_text='Any special requirements or accommodations', null=True, verbose_name='Special Requirements'),
        ),
    ]
