# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(help_text='Detailed description of the event', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(help_text='Detailed description of the event', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uz',
            field=models.TextField(help_text='Detailed description of the event', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(help_text='General location of the event', max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(help_text='General location of the event', max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(help_text='General location of the event', max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_en',
            field=models.TextField(help_text='Brief summary of the event', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_ru',
            field=models.TextField(help_text='Brief summary of the event', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_uz',
            field=models.TextField(help_text='Brief summary of the event', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags_en',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags_ru',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags_uz',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(help_text='Title of the event', max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(help_text='Title of the event', max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(help_text='Title of the event', max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_en',
            field=models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_en',
            field=models.CharField(help_text='Name of the event category', max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ru',
            field=models.CharField(help_text='Name of the event category', max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_uz',
            field=models.CharField(help_text='Name of the event category', max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='caption_en',
            field=models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='caption_ru',
            field=models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='caption_uz',
            field=models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, null=True, verbose_name='Caption'),
        ),
    ]
