# Generated by Django 5.2.7 on 2025-11-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='materials_link',
            field=models.URLField(blank=True, verbose_name='Materials Link'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, verbose_name='Registration Link'),
        ),
    ]
