# Generated by Django 5.2.7 on 2026-03-18 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEmployerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Employer business category name, for example Bank', max_length=150, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Event Employer Category',
                'verbose_name_plural': 'Event Employer Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of participants allowed for this event', verbose_name='Maximum Participants'),
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_employer_categories',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to allow employers from all business categories', related_name='events', to='events.eventemployercategory', verbose_name='Allowed Employer Categories'),
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('employer', 'Employer'), ('admin', 'Admin')], help_text='User role at the moment of registration', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=20, verbose_name='Participation Status')),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'Absent')], default='registered', max_length=20, verbose_name='Attendance Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked In At')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Token')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_participations', to=settings.AUTH_USER_MODEL, verbose_name='Checked In By')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event Participation',
                'verbose_name_plural': 'Event Participations',
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_participation_per_user')],
            },
        ),
    ]
