# Generated by Django 5.2.7 on 2026-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventemployercategory_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='attendance_code',
            field=models.CharField(default=1, editable=False, help_text='Unique code used for QR check-in.', max_length=24, unique=True, verbose_name='Attendance Code'),
            preserve_default=False,
        ),
    ]
