# Generated by Django 5.2.7 on 2026-04-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventparticipation_attendance_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='events.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event this photo belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='events.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
    ]
