# Generated by Django 5.2.7 on 2026-04-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventparticipation_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('employer', 'Employer'), ('admin', 'Admin')], help_text='User role at the moment of registration', max_length=20, verbose_name='Role'),
        ),
    ]
