# Generated by Django 5.2.7 on 2026-04-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventparticipation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_admins',
            field=models.BooleanField(default=True, help_text='Allow admin users to register for this event', verbose_name='Allow Admins'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_alumni',
            field=models.BooleanField(default=True, help_text='Allow alumni to register for this event', verbose_name='Allow Alumni'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_employers',
            field=models.BooleanField(default=True, help_text='Allow employers to register for this event', verbose_name='Allow Employers'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_students',
            field=models.BooleanField(default=True, help_text='Allow students to register for this event', verbose_name='Allow Students'),
        ),
    ]
