# Generated by Django 5.2.7 on 2026-05-11 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_alter_company_owner'),
        ('cvbuilder', '0007_alter_cv_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the position title', max_length=200, verbose_name='Job Title')),
                ('description', models.TextField(help_text='Detailed description of the job responsibilities', verbose_name='Job Description')),
                ('short_description', models.CharField(help_text='Brief summary of the job', max_length=300, verbose_name='Short Description')),
                ('job_market', models.CharField(choices=[('uzbekistan', 'Jobs in Uzbekistan'), ('abroad', 'Jobs Abroad')], default='uzbekistan', help_text='Select whether this vacancy is in Uzbekistan or abroad', max_length=20, verbose_name='Vacancy Geography')),
                ('location', models.CharField(blank=True, default='', help_text='Specific location or address', max_length=100, verbose_name='Location')),
                ('district', models.CharField(blank=True, help_text='District or city name', max_length=100, verbose_name='District/City')),
                ('region', models.CharField(blank=True, help_text='Region or province', max_length=100, verbose_name='Region')),
                ('work_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')], help_text='Type of work arrangement', max_length=20, verbose_name='Work Type')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('freelance', 'Freelance'), ('shift', 'Shift Work'), ('flexible', 'Flexible Schedule')], help_text='Type of employment contract', max_length=20, verbose_name='Employment Type')),
                ('experience_level', models.CharField(choices=[('no_experience', 'No Experience Required'), ('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director')], help_text='Required experience level', max_length=20, verbose_name='Experience Level')),
                ('education_level', models.CharField(choices=[('school', 'High School'), ('college', 'College'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('none', 'No Education Required')], help_text='Required education level', max_length=20, verbose_name='Education Level')),
                ('target_user_types', models.JSONField(blank=True, default=list, help_text="User types this job is targeted for (e.g., ['student', 'alumni'])", verbose_name='Target User Types')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary amount', max_digits=15, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary amount', max_digits=15, null=True, verbose_name='Maximum Salary')),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], default='UZS', help_text='Salary currency', max_length=3, verbose_name='Currency')),
                ('hide_salary', models.BooleanField(default=False, help_text='Hide salary information from public view', verbose_name='Hide Salary')),
                ('salary_negotiable', models.BooleanField(default=False, help_text='Salary is open to negotiation', verbose_name='Salary Negotiable')),
                ('bonus_system', models.BooleanField(default=False, help_text='Company offers bonus system', verbose_name='Bonus System')),
                ('kpi_bonus', models.BooleanField(default=False, help_text='Bonuses based on KPI performance', verbose_name='KPI Bonus')),
                ('performance_bonus', models.BooleanField(default=False, help_text='Bonuses based on overall performance', verbose_name='Performance Bonus')),
                ('requirements', models.TextField(help_text='Job requirements and qualifications', verbose_name='Requirements')),
                ('responsibilities', models.TextField(help_text='Job duties and responsibilities', verbose_name='Responsibilities')),
                ('benefits', models.TextField(blank=True, help_text='Employee benefits and perks', verbose_name='Benefits')),
                ('skills_required', models.TextField(help_text='List required skills separated by commas', verbose_name='Required Skills')),
                ('preferred_skills', models.TextField(blank=True, help_text='List preferred skills separated by commas', verbose_name='Preferred Skills')),
                ('language_requirements', models.TextField(blank=True, help_text='Required language proficiency levels', verbose_name='Language Requirements')),
                ('contact_email', models.EmailField(help_text='Email for job applications', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, help_text='Phone number for inquiries', max_length=20, verbose_name='Contact Phone')),
                ('contact_person', models.CharField(blank=True, help_text='Name of the contact person', max_length=100, verbose_name='Contact Person')),
                ('application_url', models.URLField(blank=True, help_text='Direct link to apply', verbose_name='Application URL')),
                ('work_schedule', models.CharField(blank=True, help_text='Working hours and days', max_length=100, verbose_name='Work Schedule')),
                ('probation_period', models.CharField(blank=True, help_text='Duration of probation period', max_length=50, verbose_name='Probation Period')),
                ('is_active', models.BooleanField(default=True, help_text='Job is currently active', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this job in listings', verbose_name='Featured')),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent hiring', verbose_name='Urgent')),
                ('is_premium', models.BooleanField(default=False, help_text='Premium job listing', verbose_name='Premium')),
                ('views_count', models.IntegerField(default=0, help_text='Number of views', verbose_name='Views Count')),
                ('applications_count', models.IntegerField(default=0, help_text='Number of applications received', verbose_name='Applications Count')),
                ('favorites_count', models.IntegerField(default=0, help_text='Number of times saved as favorite', verbose_name='Favorites Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Job posting expiration date', null=True, verbose_name='Expires At')),
                ('industry', models.CharField(blank=True, help_text='The industry of the job (e.g., IT, Finance, Healthcare)', max_length=100, null=True, verbose_name='Industry')),
                ('candidate_type', models.CharField(choices=[('all', 'All candidates'), ('students', 'Students'), ('graduates', 'Graduates')], default='all', help_text='Restrict applications to students, graduates, or allow all.', max_length=20, verbose_name='Allowed Candidate Type')),
                ('gender_requirement', models.CharField(choices=[('all', 'All genders'), ('female', 'Female only'), ('male', 'Male only')], default='all', help_text='Restrict applications by candidate gender.', max_length=20, verbose_name='Applicant Gender')),
                ('company', models.ForeignKey(blank=True, help_text='The company offering this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to='accounts.employerprofile', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this job alert', max_length=100, verbose_name='Alert Name')),
                ('keywords', models.CharField(blank=True, help_text='Keywords to search for in jobs', max_length=200, verbose_name='Keywords')),
                ('location', models.CharField(blank=True, help_text='Preferred job location', max_length=100, verbose_name='Location')),
                ('industry', models.CharField(blank=True, help_text='The industry of the job (e.g., IT, Finance, Healthcare)', max_length=150, null=True, verbose_name='Industry')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('freelance', 'Freelance'), ('shift', 'Shift Work'), ('flexible', 'Flexible Schedule')], help_text='Preferred employment type', max_length=20, verbose_name='Employment Type')),
                ('experience_level', models.CharField(blank=True, choices=[('no_experience', 'No Experience Required'), ('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director')], help_text='Preferred experience level', max_length=20, verbose_name='Experience Level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is active', verbose_name='Active')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to send notifications', max_length=10, verbose_name='Frequency')),
                ('last_sent', models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True, verbose_name='Last Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, help_text='User who created the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alert_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text="Candidate's cover letter explaining their interest", verbose_name='Cover Letter')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, help_text="Candidate's expected salary", max_digits=15, null=True, verbose_name='Expected Salary')),
                ('notice_period', models.IntegerField(default=0, help_text='Days required for notice period', verbose_name='Notice Period')),
                ('available_from', models.DateField(blank=True, help_text='Date when candidate can start work', null=True, verbose_name='Available From')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='applied', help_text='Current application status', max_length=20, verbose_name='Status')),
                ('status_changed_at', models.DateTimeField(auto_now=True, help_text='When status was last updated', verbose_name='Status Changed')),
                ('is_read', models.BooleanField(default=False, help_text='Whether employer has read this application', verbose_name='Read by Employer')),
                ('source', models.CharField(blank=True, help_text='How the candidate found this job', max_length=50, verbose_name='Application Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cv', models.ForeignKey(blank=True, help_text="Candidate's resume/CV", null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvbuilder.cv', verbose_name='Resume')),
                ('job', models.ForeignKey(help_text='The job being applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(blank=True, help_text='The user applying for the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note text', verbose_name='Note')),
                ('is_private', models.BooleanField(default=True, help_text='If true, only the author can see this note', verbose_name='Private Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(blank=True, help_text='User who created the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_notes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('application', models.ForeignKey(blank=True, help_text='The job application this note is attached to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='jobs.jobapplication', verbose_name='Job Application')),
            ],
            options={
                'verbose_name': 'Application Note',
                'verbose_name_plural': 'Application Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was saved', verbose_name='Saved At')),
                ('job', models.ForeignKey(help_text='The saved job', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(blank=True, help_text='User who saved the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, help_text='When the user first opened this job', verbose_name='First Viewed At')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, help_text='When the user most recently opened this job', verbose_name='Last Viewed At')),
                ('job', models.ForeignKey(help_text='The viewed job', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Viewed Job',
                'verbose_name_plural': 'Viewed Jobs',
                'ordering': ['-last_viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'is_featured'], name='jobs_job_is_acti_fc8c35_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_market', 'is_active'], name='jobs_job_job_mar_d60c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type', 'experience_level'], name='jobs_job_employm_a5cc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['region', 'district'], name='jobs_job_region_8a1bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['industry'], name='jobs_job_industr_a3aeef_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'is_active'], name='jobs_job_company_11c594_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='viewedjob',
            unique_together={('user', 'job')},
        ),
    ]
