# Generated by Django 5.2.7 on 2025-11-17 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cvbuilder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Industry Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Lavozim nomi')),
                ('description', models.TextField(verbose_name='Ish haqida batafsil')),
                ('short_description', models.CharField(max_length=300, verbose_name='Qisqacha tavsif')),
                ('location', models.CharField(blank=True, default='Kiritilmagan', max_length=100, verbose_name='Ish joyi manzili')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman/Shahar')),
                ('region', models.CharField(blank=True, default='Kiritilmagan', max_length=100, verbose_name='Viloyat')),
                ('work_type', models.CharField(choices=[('remote', 'Uydan ishlash'), ('hybrid', 'Gibrid ishlash'), ('office', 'Ishxonada ishlash')], max_length=20, verbose_name='Ish tipi')),
                ('employment_type', models.CharField(choices=[('full_time', "To'liq ish kuni"), ('part_time', 'Yarim ish kuni'), ('contract', 'Kontrakt asosida'), ('internship', 'Stajyorlik'), ('remote', 'Masofaviy ish'), ('freelance', 'Frilans'), ('shift', 'Smenali ish'), ('flexible', 'Moslashuvchan grafik')], max_length=20, verbose_name='Ish turi')),
                ('experience_level', models.CharField(choices=[('no_experience', 'Tajriba talab qilinmaydi'), ('intern', 'Stajyor'), ('junior', 'Yosh mutaxassis'), ('middle', "O'rta daraja"), ('senior', 'Katta mutaxassis'), ('lead', 'Lid'), ('manager', 'Menejer'), ('director', 'Rahbar')], max_length=20, verbose_name='Tajriba darajasi')),
                ('education_level', models.CharField(choices=[('school', "O'rta ma'lumot"), ('college', "O'rta maxsus"), ('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD'), ('none', "Ma'lumot talab qilinmaydi")], max_length=20, verbose_name="Ma'lumot darajasi")),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimal maosh')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maksimal maosh')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'AQSH dollari'), ('EUR', 'Yevro')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('hide_salary', models.BooleanField(default=False, verbose_name='Maoshnni yashirish')),
                ('salary_negotiable', models.BooleanField(default=False, verbose_name='Maosh kelishilgan holda')),
                ('bonus_system', models.BooleanField(default=False, verbose_name='Bonus tizimi')),
                ('kpi_bonus', models.BooleanField(default=False, verbose_name='KPI asosida bonus')),
                ('performance_bonus', models.BooleanField(default=False, verbose_name="Ish natijasiga ko'ra bonus")),
                ('requirements', models.TextField(verbose_name='Talablar')),
                ('responsibilities', models.TextField(verbose_name='Majburiyatlar')),
                ('benefits', models.TextField(blank=True, verbose_name='Ish shartlari va imtiyozlar')),
                ('skills_required', models.TextField(help_text="Ko'nikmalarni vergul bilan ajrating", verbose_name="Talab qilinadigan ko'nikmalar")),
                ('preferred_skills', models.TextField(blank=True, verbose_name="Qo'shimcha ko'nikmalar")),
                ('language_requirements', models.TextField(blank=True, help_text="Masalan: Ingliz tili - O'rta daraja", verbose_name='Til bilish darajasi')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Aloqa uchun email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name="Mas'ul shaxs")),
                ('application_url', models.URLField(blank=True, verbose_name='Ariza topshirish havolasi')),
                ('work_schedule', models.CharField(blank=True, help_text='Masalan: 09:00 - 18:00, dam olish kunlari: Shanba, Yakshanba', max_length=100, verbose_name='Ish jadvali')),
                ('probation_period', models.CharField(blank=True, help_text='Masalan: 3 oy', max_length=50, verbose_name='Sinov muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol vakansiya')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Shoshilinch')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium vakansiya')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('applications_count', models.IntegerField(default=0, verbose_name='Arizalar soni')),
                ('favorites_count', models.IntegerField(default=0, verbose_name='Saqlanganlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Muddati tugaydigan sana')),
                ('remote_work', models.BooleanField(default=False, verbose_name='Uzoq ish')),
                ('hybrid_work', models.BooleanField(default=False, verbose_name='Gibrid ish')),
                ('office_work', models.BooleanField(default=False, verbose_name='Ofisda ish')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.employerprofile', verbose_name='Ish beruvchi')),
            ],
            options={
                'verbose_name': "Ish o'rini",
                'verbose_name_plural': "Ish o'rinlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alert Name')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Keywords')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', "To'liq ish kuni"), ('part_time', 'Yarim ish kuni'), ('contract', 'Kontrakt asosida'), ('internship', 'Stajyorlik'), ('remote', 'Masofaviy ish'), ('freelance', 'Frilans'), ('shift', 'Smenali ish'), ('flexible', 'Moslashuvchan grafik')], max_length=20, verbose_name='Employment Type')),
                ('experience_level', models.CharField(blank=True, choices=[('no_experience', 'Tajriba talab qilinmaydi'), ('intern', 'Stajyor'), ('junior', 'Yosh mutaxassis'), ('middle', "O'rta daraja"), ('senior', 'Katta mutaxassis'), ('lead', 'Lid'), ('manager', 'Menejer'), ('director', 'Rahbar')], max_length=20, verbose_name='Experience Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10, verbose_name='Frequency')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Last Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.industry', verbose_name='Industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alert_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='Cover Letter')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected Salary')),
                ('notice_period', models.IntegerField(default=0, help_text='Days', verbose_name='Notice Period')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20, verbose_name='Status')),
                ('status_changed_at', models.DateTimeField(auto_now=True, verbose_name='Status Changed')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read by Employer')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Application Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvbuilder.cv', verbose_name='Resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Saved At')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'is_featured'], name='jobs_job_is_acti_fc8c35_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type', 'experience_level'], name='jobs_job_employm_a5cc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['region', 'district'], name='jobs_job_region_8a1bf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
