# Generated by Django 5.2.7 on 2025-11-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='industry',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='industry',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Industry Name'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Industry Name'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Industry Name'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ish shartlari va imtiyozlar'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ish shartlari va imtiyozlar'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Ish shartlari va imtiyozlar'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mas'ul shaxs"),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mas'ul shaxs"),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mas'ul shaxs"),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Ish haqida batafsil'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Ish haqida batafsil'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Ish haqida batafsil'),
        ),
        migrations.AddField(
            model_name='job',
            name='district_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='job',
            name='district_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='job',
            name='district_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='job',
            name='language_requirements_en',
            field=models.TextField(blank=True, help_text="Masalan: Ingliz tili - O'rta daraja", null=True, verbose_name='Til bilish darajasi'),
        ),
        migrations.AddField(
            model_name='job',
            name='language_requirements_ru',
            field=models.TextField(blank=True, help_text="Masalan: Ingliz tili - O'rta daraja", null=True, verbose_name='Til bilish darajasi'),
        ),
        migrations.AddField(
            model_name='job',
            name='language_requirements_uz',
            field=models.TextField(blank=True, help_text="Masalan: Ingliz tili - O'rta daraja", null=True, verbose_name='Til bilish darajasi'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_en',
            field=models.CharField(blank=True, default='Kiritilmagan', max_length=100, null=True, verbose_name='Ish joyi manzili'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_ru',
            field=models.CharField(blank=True, default='Kiritilmagan', max_length=100, null=True, verbose_name='Ish joyi manzili'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_uz',
            field=models.CharField(blank=True, default='Kiritilmagan', max_length=100, null=True, verbose_name='Ish joyi manzili'),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills_en',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ko'nikmalar"),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ko'nikmalar"),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ko'nikmalar"),
        ),
        migrations.AddField(
            model_name='job',
            name='probation_period_en',
            field=models.CharField(blank=True, help_text='Masalan: 3 oy', max_length=50, null=True, verbose_name='Sinov muddati'),
        ),
        migrations.AddField(
            model_name='job',
            name='probation_period_ru',
            field=models.CharField(blank=True, help_text='Masalan: 3 oy', max_length=50, null=True, verbose_name='Sinov muddati'),
        ),
        migrations.AddField(
            model_name='job',
            name='probation_period_uz',
            field=models.CharField(blank=True, help_text='Masalan: 3 oy', max_length=50, null=True, verbose_name='Sinov muddati'),
        ),
        migrations.AddField(
            model_name='job',
            name='region_en',
            field=models.CharField(blank=True, default='Kiritilmagan', max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='job',
            name='region_ru',
            field=models.CharField(blank=True, default='Kiritilmagan', max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='job',
            name='region_uz',
            field=models.CharField(blank=True, default='Kiritilmagan', max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_en',
            field=models.TextField(null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_ru',
            field=models.TextField(null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_uz',
            field=models.TextField(null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_en',
            field=models.TextField(null=True, verbose_name='Majburiyatlar'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_ru',
            field=models.TextField(null=True, verbose_name='Majburiyatlar'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_uz',
            field=models.TextField(null=True, verbose_name='Majburiyatlar'),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_en',
            field=models.TextField(help_text="Ko'nikmalarni vergul bilan ajrating", null=True, verbose_name="Talab qilinadigan ko'nikmalar"),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_ru',
            field=models.TextField(help_text="Ko'nikmalarni vergul bilan ajrating", null=True, verbose_name="Talab qilinadigan ko'nikmalar"),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_uz',
            field=models.TextField(help_text="Ko'nikmalarni vergul bilan ajrating", null=True, verbose_name="Talab qilinadigan ko'nikmalar"),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim nomi'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim nomi'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim nomi'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule_en',
            field=models.CharField(blank=True, help_text='Masalan: 09:00 - 18:00, dam olish kunlari: Shanba, Yakshanba', max_length=100, null=True, verbose_name='Ish jadvali'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule_ru',
            field=models.CharField(blank=True, help_text='Masalan: 09:00 - 18:00, dam olish kunlari: Shanba, Yakshanba', max_length=100, null=True, verbose_name='Ish jadvali'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule_uz',
            field=models.CharField(blank=True, help_text='Masalan: 09:00 - 18:00, dam olish kunlari: Shanba, Yakshanba', max_length=100, null=True, verbose_name='Ish jadvali'),
        ),
    ]
