# Generated by Django 5.2.7 on 2025-11-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="short_description",
            field=models.CharField(max_length=300, verbose_name="Short Description"),
        ),
    ]
