# Generated by Django 5.2.7 on 2025-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tuman/Shahar", default=""
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="region",
            field=models.CharField(
                default="Toshkent", max_length=100, verbose_name="Viloyat"
            ),
        ),
    ]
