# Generated by Django 5.2.7 on 2026-03-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminprofile_can_change_company_status_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_market',
            field=models.CharField(choices=[('uzbekistan', 'Jobs in Uzbekistan'), ('abroad', 'Jobs Abroad')], default='uzbekistan', help_text='Select whether this vacancy is in Uzbekistan or abroad', max_length=20, verbose_name='Vacancy Geography'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_market', 'is_active'], name='jobs_job_job_mar_d60c5f_idx'),
        ),
    ]
