# Generated by Django 5.2.7 on 2025-11-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_auto_20251113_1722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tuman/Shahar"
            ),
        ),
    ]
