# Generated by Django 5.2.7 on 2025-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_industry_description_en_industry_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='keywords_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='location_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='location_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='location_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Alert Name'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Alert Name'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Alert Name'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_en',
            field=models.TextField(null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_ru',
            field=models.TextField(null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_uz',
            field=models.TextField(null=True, verbose_name='Cover Letter'),
        ),
    ]
