# Generated by Django 5.2.7 on 2026-03-24 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_market_job_jobs_job_job_mar_d60c5f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, help_text='When the user first opened this job', verbose_name='First Viewed At')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, help_text='When the user most recently opened this job', verbose_name='Last Viewed At')),
                ('job', models.ForeignKey(help_text='The viewed job', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(help_text='User who viewed the job', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Viewed Job',
                'verbose_name_plural': 'Viewed Jobs',
                'ordering': ['-last_viewed_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
