# Generated by Django 5.2.7 on 2026-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_viewedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidate_type',
            field=models.CharField(choices=[('all', 'All candidates'), ('students', 'Students'), ('graduates', 'Graduates')], default='all', help_text='Restrict applications to students, graduates, or allow all.', max_length=20, verbose_name='Allowed Candidate Type'),
        ),
        migrations.AddField(
            model_name='job',
            name='gender_requirement',
            field=models.CharField(choices=[('all', 'All genders'), ('female', 'Female only'), ('male', 'Male only')], default='all', help_text='Restrict applications by candidate gender.', max_length=20, verbose_name='Applicant Gender'),
        ),
    ]
