# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='description_en',
            field=models.TextField(blank=True, help_text='Optional description of the industry', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='industry',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Optional description of the industry', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='industry',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Optional description of the industry', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_en',
            field=models.CharField(help_text='Name of the industry sector', max_length=100, null=True, verbose_name='Industry Name'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_ru',
            field=models.CharField(help_text='Name of the industry sector', max_length=100, null=True, verbose_name='Industry Name'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_uz',
            field=models.CharField(help_text='Name of the industry sector', max_length=100, null=True, verbose_name='Industry Name'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_en',
            field=models.TextField(blank=True, help_text='Employee benefits and perks', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_ru',
            field=models.TextField(blank=True, help_text='Employee benefits and perks', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_uz',
            field=models.TextField(blank=True, help_text='Employee benefits and perks', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_en',
            field=models.CharField(blank=True, help_text='Name of the contact person', max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_ru',
            field=models.CharField(blank=True, help_text='Name of the contact person', max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_uz',
            field=models.CharField(blank=True, help_text='Name of the contact person', max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(help_text='Detailed description of the job responsibilities', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_ru',
            field=models.TextField(help_text='Detailed description of the job responsibilities', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_uz',
            field=models.TextField(help_text='Detailed description of the job responsibilities', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='district_en',
            field=models.CharField(blank=True, help_text='District or city name', max_length=100, null=True, verbose_name='District/City'),
        ),
        migrations.AddField(
            model_name='job',
            name='district_ru',
            field=models.CharField(blank=True, help_text='District or city name', max_length=100, null=True, verbose_name='District/City'),
        ),
        migrations.AddField(
            model_name='job',
            name='district_uz',
            field=models.CharField(blank=True, help_text='District or city name', max_length=100, null=True, verbose_name='District/City'),
        ),
        migrations.AddField(
            model_name='job',
            name='language_requirements_en',
            field=models.TextField(blank=True, help_text='Required language proficiency levels', null=True, verbose_name='Language Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='language_requirements_ru',
            field=models.TextField(blank=True, help_text='Required language proficiency levels', null=True, verbose_name='Language Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='language_requirements_uz',
            field=models.TextField(blank=True, help_text='Required language proficiency levels', null=True, verbose_name='Language Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_en',
            field=models.CharField(blank=True, default='', help_text='Specific location or address', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_ru',
            field=models.CharField(blank=True, default='', help_text='Specific location or address', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_uz',
            field=models.CharField(blank=True, default='', help_text='Specific location or address', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills_en',
            field=models.TextField(blank=True, help_text='List preferred skills separated by commas', null=True, verbose_name='Preferred Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills_ru',
            field=models.TextField(blank=True, help_text='List preferred skills separated by commas', null=True, verbose_name='Preferred Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills_uz',
            field=models.TextField(blank=True, help_text='List preferred skills separated by commas', null=True, verbose_name='Preferred Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='probation_period_en',
            field=models.CharField(blank=True, help_text='Duration of probation period', max_length=50, null=True, verbose_name='Probation Period'),
        ),
        migrations.AddField(
            model_name='job',
            name='probation_period_ru',
            field=models.CharField(blank=True, help_text='Duration of probation period', max_length=50, null=True, verbose_name='Probation Period'),
        ),
        migrations.AddField(
            model_name='job',
            name='probation_period_uz',
            field=models.CharField(blank=True, help_text='Duration of probation period', max_length=50, null=True, verbose_name='Probation Period'),
        ),
        migrations.AddField(
            model_name='job',
            name='region_en',
            field=models.CharField(blank=True, help_text='Region or province', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='job',
            name='region_ru',
            field=models.CharField(blank=True, help_text='Region or province', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='job',
            name='region_uz',
            field=models.CharField(blank=True, help_text='Region or province', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_en',
            field=models.TextField(help_text='Job requirements and qualifications', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_ru',
            field=models.TextField(help_text='Job requirements and qualifications', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_uz',
            field=models.TextField(help_text='Job requirements and qualifications', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_en',
            field=models.TextField(help_text='Job duties and responsibilities', null=True, verbose_name='Responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_ru',
            field=models.TextField(help_text='Job duties and responsibilities', null=True, verbose_name='Responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_uz',
            field=models.TextField(help_text='Job duties and responsibilities', null=True, verbose_name='Responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_en',
            field=models.CharField(help_text='Brief summary of the job', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_ru',
            field=models.CharField(help_text='Brief summary of the job', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_uz',
            field=models.CharField(help_text='Brief summary of the job', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_en',
            field=models.TextField(help_text='List required skills separated by commas', null=True, verbose_name='Required Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_ru',
            field=models.TextField(help_text='List required skills separated by commas', null=True, verbose_name='Required Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required_uz',
            field=models.TextField(help_text='List required skills separated by commas', null=True, verbose_name='Required Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(help_text='Enter the position title', max_length=200, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_ru',
            field=models.CharField(help_text='Enter the position title', max_length=200, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_uz',
            field=models.CharField(help_text='Enter the position title', max_length=200, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule_en',
            field=models.CharField(blank=True, help_text='Working hours and days', max_length=100, null=True, verbose_name='Work Schedule'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule_ru',
            field=models.CharField(blank=True, help_text='Working hours and days', max_length=100, null=True, verbose_name='Work Schedule'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule_uz',
            field=models.CharField(blank=True, help_text='Working hours and days', max_length=100, null=True, verbose_name='Work Schedule'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='keywords_en',
            field=models.CharField(blank=True, help_text='Keywords to search for in jobs', max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='keywords_ru',
            field=models.CharField(blank=True, help_text='Keywords to search for in jobs', max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='keywords_uz',
            field=models.CharField(blank=True, help_text='Keywords to search for in jobs', max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='location_en',
            field=models.CharField(blank=True, help_text='Preferred job location', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='location_ru',
            field=models.CharField(blank=True, help_text='Preferred job location', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='location_uz',
            field=models.CharField(blank=True, help_text='Preferred job location', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='name_en',
            field=models.CharField(help_text='Name for this job alert', max_length=100, null=True, verbose_name='Alert Name'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='name_ru',
            field=models.CharField(help_text='Name for this job alert', max_length=100, null=True, verbose_name='Alert Name'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='name_uz',
            field=models.CharField(help_text='Name for this job alert', max_length=100, null=True, verbose_name='Alert Name'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_en',
            field=models.TextField(help_text="Candidate's cover letter explaining their interest", null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_ru',
            field=models.TextField(help_text="Candidate's cover letter explaining their interest", null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_uz',
            field=models.TextField(help_text="Candidate's cover letter explaining their interest", null=True, verbose_name='Cover Letter'),
        ),
    ]
