# Generated by Django 5.2.7 on 2026-04-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_oauth_degree_and_more'),
        ('jobs', '0004_job_candidate_type_job_gender_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The job application this note is attached to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='jobs.jobapplication', verbose_name='Job Application'),
        ),
        migrations.AlterField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(blank=True, help_text='User who created the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_notes', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company offering this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to='accounts.employerprofile', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alert_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user applying for the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who saved the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='viewedjob',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who viewed the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
