# Generated by Django 5.2.7 on 2026-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_applicationnote_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='target_user_types',
            field=models.JSONField(blank=True, default=list, help_text="User types this job is targeted for (e.g., ['student', 'alumni'])", verbose_name='Target User Types'),
        ),
    ]
