# Generated by Django 5.2.7 on 2026-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_target_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Candidate's expected salary", max_digits=15, null=True, verbose_name='Expected Salary'),
        ),
    ]
