# Generated by Django 5.2.7 on 2025-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='city_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_position_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_position_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_position_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='expertise_areas_en',
            field=models.TextField(blank=True, help_text='Mutaxassislik sohalarini vergul bilan ajrating', null=True, verbose_name='Mutaxassislik sohalari'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='expertise_areas_ru',
            field=models.TextField(blank=True, help_text='Mutaxassislik sohalarini vergul bilan ajrating', null=True, verbose_name='Mutaxassislik sohalari'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='expertise_areas_uz',
            field=models.TextField(blank=True, help_text='Mutaxassislik sohalarini vergul bilan ajrating', null=True, verbose_name='Mutaxassislik sohalari'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='faculty_en',
            field=models.CharField(choices=[('engineering', 'Dasturiy injiniring'), ('economics', 'Iqtisodiyot'), ('management', 'Boshqaruv'), ('law', 'Huquqshunoslik'), ('philology', 'Filologiya'), ('foreign_languages', 'Chet tillari'), ('journalism', 'Jurnalistika'), ('international_relations', 'Xalqaro munosabatlar')], max_length=100, null=True, verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='faculty_ru',
            field=models.CharField(choices=[('engineering', 'Dasturiy injiniring'), ('economics', 'Iqtisodiyot'), ('management', 'Boshqaruv'), ('law', 'Huquqshunoslik'), ('philology', 'Filologiya'), ('foreign_languages', 'Chet tillari'), ('journalism', 'Jurnalistika'), ('international_relations', 'Xalqaro munosabatlar')], max_length=100, null=True, verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='faculty_uz',
            field=models.CharField(choices=[('engineering', 'Dasturiy injiniring'), ('economics', 'Iqtisodiyot'), ('management', 'Boshqaruv'), ('law', 'Huquqshunoslik'), ('philology', 'Filologiya'), ('foreign_languages', 'Chet tillari'), ('journalism', 'Jurnalistika'), ('international_relations', 'Xalqaro munosabatlar')], max_length=100, null=True, verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='industry_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soha'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='industry_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soha'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='industry_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soha'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profession_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kasb'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profession_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kasb'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profession_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kasb'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='specialization_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='specialization_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='specialization_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='connection',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='connection',
            name='message_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='connection',
            name='message_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_en',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalliklar'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalliklar'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalliklar'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_en',
            field=models.TextField(null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_ru',
            field=models.TextField(null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_uz',
            field=models.TextField(null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xat'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xat'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Xat'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='expected_duration_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kutilayotgan davomiylik'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='expected_duration_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kutilayotgan davomiylik'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='expected_duration_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kutilayotgan davomiylik'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_feedback_en',
            field=models.TextField(blank=True, null=True, verbose_name='Menti fikri'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_feedback_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Menti fikri'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_feedback_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Menti fikri'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor_feedback_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mentor fikri'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor_feedback_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Mentor fikri'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor_feedback_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Mentor fikri'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='message_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='message_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='message',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Xabar matni'),
        ),
        migrations.AddField(
            model_name='message',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Xabar matni'),
        ),
        migrations.AddField(
            model_name='message',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Xabar matni'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Mazmuni'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Mazmuni'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Mazmuni'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teglar'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teglar'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teglar'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name="Ko'nikma nomi"),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="Ko'nikma nomi"),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="Ko'nikma nomi"),
        ),
    ]
