# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_remove_alumni_bio_en_remove_alumni_bio_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='bio_en',
            field=models.TextField(blank=True, help_text='Professional biography or summary', null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='bio_ru',
            field=models.TextField(blank=True, help_text='Professional biography or summary', null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='bio_uz',
            field=models.TextField(blank=True, help_text='Professional biography or summary', null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='city_en',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='city_ru',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='city_uz',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_position_en',
            field=models.CharField(blank=True, help_text='Current job title or position', max_length=255, null=True, verbose_name='Current Position'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_position_ru',
            field=models.CharField(blank=True, help_text='Current job title or position', max_length=255, null=True, verbose_name='Current Position'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_position_uz',
            field=models.CharField(blank=True, help_text='Current job title or position', max_length=255, null=True, verbose_name='Current Position'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='expertise_areas_en',
            field=models.TextField(blank=True, help_text='Separate expertise areas with commas', null=True, verbose_name='Expertise Areas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='expertise_areas_ru',
            field=models.TextField(blank=True, help_text='Separate expertise areas with commas', null=True, verbose_name='Expertise Areas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='expertise_areas_uz',
            field=models.TextField(blank=True, help_text='Separate expertise areas with commas', null=True, verbose_name='Expertise Areas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='faculty_en',
            field=models.CharField(choices=[('engineering', 'Software Engineering'), ('economics', 'Economics'), ('management', 'Management'), ('law', 'Law'), ('philology', 'Philology'), ('foreign_languages', 'Foreign Languages'), ('journalism', 'Journalism'), ('international_relations', 'International Relations')], help_text='Academic faculty or department', max_length=100, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='faculty_ru',
            field=models.CharField(choices=[('engineering', 'Software Engineering'), ('economics', 'Economics'), ('management', 'Management'), ('law', 'Law'), ('philology', 'Philology'), ('foreign_languages', 'Foreign Languages'), ('journalism', 'Journalism'), ('international_relations', 'International Relations')], help_text='Academic faculty or department', max_length=100, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='faculty_uz',
            field=models.CharField(choices=[('engineering', 'Software Engineering'), ('economics', 'Economics'), ('management', 'Management'), ('law', 'Law'), ('philology', 'Philology'), ('foreign_languages', 'Foreign Languages'), ('journalism', 'Journalism'), ('international_relations', 'International Relations')], help_text='Academic faculty or department', max_length=100, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='industry_en',
            field=models.CharField(blank=True, help_text='Industry sector', max_length=100, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='industry_ru',
            field=models.CharField(blank=True, help_text='Industry sector', max_length=100, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='industry_uz',
            field=models.CharField(blank=True, help_text='Industry sector', max_length=100, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name_en',
            field=models.CharField(help_text="Alumni's full name", max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name_ru',
            field=models.CharField(help_text="Alumni's full name", max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name_uz',
            field=models.CharField(help_text="Alumni's full name", max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profession_en',
            field=models.CharField(blank=True, help_text='Professional field or occupation', max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profession_ru',
            field=models.CharField(blank=True, help_text='Professional field or occupation', max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profession_uz',
            field=models.CharField(blank=True, help_text='Professional field or occupation', max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='specialization_en',
            field=models.CharField(blank=True, help_text='Field of specialization', max_length=255, null=True, verbose_name='Specialization'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='specialization_ru',
            field=models.CharField(blank=True, help_text='Field of specialization', max_length=255, null=True, verbose_name='Specialization'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='specialization_uz',
            field=models.CharField(blank=True, help_text='Field of specialization', max_length=255, null=True, verbose_name='Specialization'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_en',
            field=models.TextField(blank=True, help_text='Company address', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_ru',
            field=models.TextField(blank=True, help_text='Company address', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_uz',
            field=models.TextField(blank=True, help_text='Company address', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, help_text='Company description and overview', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Company description and overview', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Company description and overview', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(help_text='Official company name', max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ru',
            field=models.CharField(help_text='Official company name', max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_uz',
            field=models.CharField(help_text='Official company name', max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='connection',
            name='message_en',
            field=models.TextField(blank=True, help_text='Optional message with connection request', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='connection',
            name='message_ru',
            field=models.TextField(blank=True, help_text='Optional message with connection request', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='connection',
            name='message_uz',
            field=models.TextField(blank=True, help_text='Optional message with connection request', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(help_text='Detailed event description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(help_text='Detailed event description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uz',
            field=models.TextField(help_text='Detailed event description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(help_text='Physical location of the event', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(help_text='Physical location of the event', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(help_text='Physical location of the event', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(help_text='Event title or name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(help_text='Event title or name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(help_text='Event title or name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_en',
            field=models.TextField(blank=True, help_text='Job benefits and perks', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_ru',
            field=models.TextField(blank=True, help_text='Job benefits and perks', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_uz',
            field=models.TextField(blank=True, help_text='Job benefits and perks', null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(help_text='Detailed job description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_ru',
            field=models.TextField(help_text='Detailed job description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_uz',
            field=models.TextField(help_text='Detailed job description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_en',
            field=models.CharField(help_text='Job location or work location', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_ru',
            field=models.CharField(help_text='Job location or work location', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_uz',
            field=models.CharField(help_text='Job location or work location', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_en',
            field=models.TextField(help_text='Job requirements and qualifications', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_ru',
            field=models.TextField(help_text='Job requirements and qualifications', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_uz',
            field=models.TextField(help_text='Job requirements and qualifications', null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(help_text='Position or job title', max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_ru',
            field=models.CharField(help_text='Position or job title', max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_uz',
            field=models.CharField(help_text='Position or job title', max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_en',
            field=models.TextField(blank=True, help_text="Applicant's cover letter", null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_ru',
            field=models.TextField(blank=True, help_text="Applicant's cover letter", null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_uz',
            field=models.TextField(blank=True, help_text="Applicant's cover letter", null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='expected_duration_en',
            field=models.CharField(blank=True, help_text='Expected duration of the mentorship program', max_length=100, null=True, verbose_name='Expected Duration'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='expected_duration_ru',
            field=models.CharField(blank=True, help_text='Expected duration of the mentorship program', max_length=100, null=True, verbose_name='Expected Duration'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='expected_duration_uz',
            field=models.CharField(blank=True, help_text='Expected duration of the mentorship program', max_length=100, null=True, verbose_name='Expected Duration'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_feedback_en',
            field=models.TextField(blank=True, help_text='Feedback from the mentee', null=True, verbose_name='Mentee Feedback'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_feedback_ru',
            field=models.TextField(blank=True, help_text='Feedback from the mentee', null=True, verbose_name='Mentee Feedback'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_feedback_uz',
            field=models.TextField(blank=True, help_text='Feedback from the mentee', null=True, verbose_name='Mentee Feedback'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor_feedback_en',
            field=models.TextField(blank=True, help_text='Feedback from the mentor', null=True, verbose_name='Mentor Feedback'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor_feedback_ru',
            field=models.TextField(blank=True, help_text='Feedback from the mentor', null=True, verbose_name='Mentor Feedback'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor_feedback_uz',
            field=models.TextField(blank=True, help_text='Feedback from the mentor', null=True, verbose_name='Mentor Feedback'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='message_en',
            field=models.TextField(blank=True, help_text='Initial message or request for mentorship', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='message_ru',
            field=models.TextField(blank=True, help_text='Initial message or request for mentorship', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='message_uz',
            field=models.TextField(blank=True, help_text='Initial message or request for mentorship', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='body_en',
            field=models.TextField(help_text='Message content', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='message',
            name='body_ru',
            field=models.TextField(help_text='Message content', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='message',
            name='body_uz',
            field=models.TextField(help_text='Message content', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_en',
            field=models.CharField(help_text='Message subject line', max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_ru',
            field=models.CharField(help_text='Message subject line', max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_uz',
            field=models.CharField(help_text='Message subject line', max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(help_text='Full news article content', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(help_text='Full news article content', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(help_text='Full news article content', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags_en',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the article', max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags_ru',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the article', max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags_uz',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the article', max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='News article title', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(help_text='News article title', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(help_text='News article title', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, help_text='Detailed description of the skill', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Detailed description of the skill', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Detailed description of the skill', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(help_text='Name of the skill or competency', max_length=100, null=True, verbose_name='Skill Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(help_text='Name of the skill or competency', max_length=100, null=True, verbose_name='Skill Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(help_text='Name of the skill or competency', max_length=100, null=True, verbose_name='Skill Name'),
        ),
    ]
