# Generated by Django 5.2.7 on 2025-11-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('subject_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('subject_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('subject_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_uz', models.TextField(null=True, verbose_name='Message')),
                ('message_ru', models.TextField(null=True, verbose_name='Message')),
                ('message_en', models.TextField(null=True, verbose_name='Message')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Status')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('admin_notes_uz', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('admin_notes_ru', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('admin_notes_en', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_contac_created_63cb1b_idx'), models.Index(fields=['status'], name='core_contac_status_de41ec_idx'), models.Index(fields=['is_processed'], name='core_contac_is_proc_dc6c16_idx')],
            },
        ),
    ]
