# Generated by Django 5.2.7 on 2026-06-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('subject_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('subject_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('subject_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_uz', models.TextField(null=True, verbose_name='Message')),
                ('message_ru', models.TextField(null=True, verbose_name='Message')),
                ('message_en', models.TextField(null=True, verbose_name='Message')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Status')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('admin_notes_uz', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('admin_notes_ru', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('admin_notes_en', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_contac_created_63cb1b_idx'), models.Index(fields=['status'], name='core_contac_status_de41ec_idx'), models.Index(fields=['is_processed'], name='core_contac_is_proc_dc6c16_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ru', models.TextField(verbose_name='Message (Russian)')),
                ('message_uz', models.TextField(blank=True, verbose_name='Message (Uzbek)')),
                ('message_en', models.TextField(blank=True, verbose_name='Message (English)')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('end_at', models.DateTimeField(verbose_name='End at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'System notification',
                'verbose_name_plural': 'System notifications',
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='Dismissed at')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='core.systemnotification', verbose_name='Notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notification_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User notification dismissal',
                'verbose_name_plural': 'User notification dismissals',
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='core_system_is_acti_1bec00_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['-start_at', '-created_at'], name='core_system_start_a_09ff75_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationdismissal',
            index=models.Index(fields=['user', 'dismissed_at'], name='core_userno_user_id_ce8f10_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationdismissal',
            index=models.Index(fields=['notification', 'dismissed_at'], name='core_userno_notific_a7f144_idx'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationdismissal',
            constraint=models.UniqueConstraint(fields=('user', 'notification'), name='core_unique_user_notification_dismissal'),
        ),
    ]
