# Generated by Django 5.2.7 on 2025-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=255, verbose_name="Тема"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("in_progress", "В обработке"),
                            ("completed", "Завершено"),
                            ("spam", "Спам"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Заметки администратора"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Сообщение обратной связи",
                "verbose_name_plural": "Сообщения обратной связи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_contac_created_63cb1b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_contac_status_de41ec_idx"
                    ),
                    models.Index(
                        fields=["is_processed"], name="core_contac_is_proc_dc6c16_idx"
                    ),
                ],
            },
        ),
    ]
