# Generated by Django 5.2.7 on 2025-11-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_notes_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_notes_ru',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_notes_uz',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject_ru',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject_uz',
        ),
    ]
