# Generated by Django 5.2.7 on 2026-03-23 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ru', models.TextField(verbose_name='Message (Russian)')),
                ('message_uz', models.TextField(blank=True, verbose_name='Message (Uzbek)')),
                ('message_en', models.TextField(blank=True, verbose_name='Message (English)')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('end_at', models.DateTimeField(verbose_name='End at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'System notification',
                'verbose_name_plural': 'System notifications',
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='Dismissed at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='core.systemnotification', verbose_name='Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notification_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User notification dismissal',
                'verbose_name_plural': 'User notification dismissals',
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='core_system_is_acti_1bec00_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['-start_at', '-created_at'], name='core_system_start_a_09ff75_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationdismissal',
            index=models.Index(fields=['user', 'dismissed_at'], name='core_userno_user_id_ce8f10_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationdismissal',
            index=models.Index(fields=['notification', 'dismissed_at'], name='core_userno_notific_a7f144_idx'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationdismissal',
            constraint=models.UniqueConstraint(fields=('user', 'notification'), name='core_unique_user_notification_dismissal'),
        ),
    ]
