# Generated by Django 5.2.7 on 2025-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_uz',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема'),
        ),
    ]
