# Generated by Django 5.2.7 on 2026-04-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemnotification_usernotificationdismissal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationdismissal',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='core.systemnotification', verbose_name='Notification'),
        ),
        migrations.AlterField(
            model_name='usernotificationdismissal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notification_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
