# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contactmessage_admin_notes_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_uz',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
    ]
