# Generated by Django 5.2.7 on 2026-01-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name received from OAuth (read-only)', max_length=255, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_locked',
            field=models.BooleanField(default=False, help_text='If True, full_name cannot be changed', verbose_name='Full name locked'),
        ),
    ]
