# Generated by Django 5.2.7 on 2025-10-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hemis_id',
        ),
    ]
