# Generated by Django 5.2.7 on 2025-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_uz',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description_en',
            field=models.TextField(null=True, verbose_name='Kompaniya haqida'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description_ru',
            field=models.TextField(null=True, verbose_name='Kompaniya haqida'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description_uz',
            field=models.TextField(null=True, verbose_name='Kompaniya haqida'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='headquarters_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bosh qarorgoh'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='headquarters_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bosh qarorgoh'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='headquarters_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bosh qarorgoh'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_uz',
            field=models.TextField(null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_position_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Istagan lavozim'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_position_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Istagan lavozim'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_position_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Istagan lavozim'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik'),
        ),
    ]
