# Generated by Django 5.2.7 on 2026-02-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_full_name_customuser_full_name_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student_avatars/%Y/%m/%d/'),
        ),
    ]
