# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_en',
            field=models.CharField(blank=True, help_text='Full address', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_ru',
            field=models.CharField(blank=True, help_text='Full address', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_uz',
            field=models.CharField(blank=True, help_text='Full address', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_en',
            field=models.TextField(blank=True, help_text='Short biography or description', max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_ru',
            field=models.TextField(blank=True, help_text='Short biography or description', max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_uz',
            field=models.TextField(blank=True, help_text='Short biography or description', max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_en',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_ru',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_uz',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description_en',
            field=models.TextField(help_text='Detailed description of the company', null=True, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description_ru',
            field=models.TextField(help_text='Detailed description of the company', null=True, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description_uz',
            field=models.TextField(help_text='Detailed description of the company', null=True, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name_en',
            field=models.CharField(help_text='Official company name', max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name_ru',
            field=models.CharField(help_text='Official company name', max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name_uz',
            field=models.CharField(help_text='Official company name', max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='headquarters_en',
            field=models.CharField(blank=True, help_text='Location of company headquarters', max_length=255, null=True, verbose_name='Headquarters'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='headquarters_ru',
            field=models.CharField(blank=True, help_text='Location of company headquarters', max_length=255, null=True, verbose_name='Headquarters'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='headquarters_uz',
            field=models.CharField(blank=True, help_text='Location of company headquarters', max_length=255, null=True, verbose_name='Headquarters'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(help_text='Full notification content', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(help_text='Full notification content', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_uz',
            field=models.TextField(help_text='Full notification content', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(help_text='Notification title or subject', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(help_text='Notification title or subject', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_uz',
            field=models.CharField(help_text='Notification title or subject', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_position_en',
            field=models.CharField(blank=True, help_text='Preferred job position or title', max_length=255, null=True, verbose_name='Desired Position'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_position_ru',
            field=models.CharField(blank=True, help_text='Preferred job position or title', max_length=255, null=True, verbose_name='Desired Position'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_position_uz',
            field=models.CharField(blank=True, help_text='Preferred job position or title', max_length=255, null=True, verbose_name='Desired Position'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_en',
            field=models.CharField(blank=True, help_text='Academic faculty or department', max_length=255, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_ru',
            field=models.CharField(blank=True, help_text='Academic faculty or department', max_length=255, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_uz',
            field=models.CharField(blank=True, help_text='Academic faculty or department', max_length=255, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty_en',
            field=models.CharField(blank=True, help_text='Field of study or specialization', max_length=255, null=True, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty_ru',
            field=models.CharField(blank=True, help_text='Field of study or specialization', max_length=255, null=True, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty_uz',
            field=models.CharField(blank=True, help_text='Field of study or specialization', max_length=255, null=True, verbose_name='Specialty'),
        ),
    ]
