# Generated by Django 5.2.7 on 2026-03-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='can_change_company_status',
            field=models.BooleanField(default=True, help_text='Permission to activate or deactivate companies', verbose_name='Change Company Status'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_change_user_status',
            field=models.BooleanField(default=True, help_text='Permission to activate or deactivate managed users', verbose_name='Change User Status'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_create_employers',
            field=models.BooleanField(default=True, help_text='Permission to create employer accounts', verbose_name='Create Employers'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_create_jobs',
            field=models.BooleanField(default=True, help_text='Permission to create jobs from the admin area', verbose_name='Create Jobs'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_manage_events',
            field=models.BooleanField(default=True, help_text='Permission to create, edit and moderate events', verbose_name='Manage Events'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_verify_companies',
            field=models.BooleanField(default=True, help_text='Permission to verify and unverify companies', verbose_name='Verify Companies'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_view_company_details',
            field=models.BooleanField(default=True, help_text='Permission to view detailed company data in the admin area', verbose_name='View Company Details'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student or Graduate'), ('employer', 'Employer'), ('admin', 'Admin'), ('international_admin', 'International Admin'), ('main_admin', 'Main Admin')], default='guest', help_text='Type of user account (guest, student, employer, admin)', max_length=20, verbose_name='User Type'),
        ),
    ]
