# Generated by Django 5.2.7 on 2026-03-23 10:55

import accounts.certificates
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminprofile_can_change_company_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Certificate name shown to employers', max_length=255, verbose_name='Certificate Title')),
                ('file', models.FileField(help_text='Upload a PDF or image certificate', storage=accounts.certificates.StudentCertificateStorage(), upload_to=accounts.certificates.student_certificate_upload_to, validators=[accounts.certificates.validate_student_certificate_file], verbose_name='Certificate File')),
                ('description', models.TextField(blank=True, help_text='Optional certificate details', verbose_name='Description')),
                ('issuer', models.CharField(blank=True, help_text='Organization that issued the certificate', max_length=255, verbose_name='Issuer')),
                ('issue_date', models.DateField(blank=True, help_text='Date when the certificate was issued', null=True, verbose_name='Issue Date')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this certificate can be shown to employers', verbose_name='Visible to Employers')),
                ('student', models.ForeignKey(help_text='Student profile that owns this certificate', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Certificate',
                'verbose_name_plural': 'Student Certificates',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='accounts_st_student_5f6bff_idx'), models.Index(fields=['-uploaded_at'], name='accounts_st_uploade_85b1fe_idx')],
            },
        ),
    ]
