# Generated by Django 5.2.7 on 2025-11-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
