# Generated by Django 5.2.7 on 2026-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/default_avatar.png', null=True, upload_to='student_avatars/%Y/%m/%d/'),
        ),
    ]
