# Generated by Django 5.2.7 on 2025-11-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_employerprofile_industry"),
    ]

    operations = []
