# Generated by Django 5.2.7 on 2025-11-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20251113_1556"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE accounts_employerprofile SET industry = NULL WHERE industry IN ('Soha haqida ma`lumot', '')",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
