# Generated by Django 5.2.7 on 2026-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender provided by OAuth or entered in profile', max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_data_locked',
            field=models.BooleanField(default=False, help_text='When enabled, OAuth-provided profile data cannot be changed by the user', verbose_name='OAuth Data Locked'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_payload',
            field=models.JSONField(blank=True, help_text='Raw OAuth provider data stored for auditing and synchronization', null=True, verbose_name='OAuth Payload'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate')], default='student', help_text='Academic status of the user, either current student or graduate', max_length=20, verbose_name='Student Status'),
        ),
    ]
