# Generated by Django 5.2.7 on 2025-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20251113_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="jobs.industry",
                verbose_name="Soha",
            ),
        ),
    ]
