# Generated by Django 5.2.7 on 2026-04-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_gender_customuser_oauth_data_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauth_degree',
            field=models.CharField(blank=True, help_text='Degree from OAuth provider', max_length=100, verbose_name='OAuth Degree'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_enrollment_year',
            field=models.IntegerField(blank=True, help_text='Year of enrollment from OAuth provider', null=True, verbose_name='OAuth Enrollment Year'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_gpa',
            field=models.FloatField(blank=True, help_text='GPA from OAuth provider', null=True, verbose_name='OAuth GPA'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last time OAuth data was synchronized', null=True, verbose_name='OAuth Last Synced'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_specialization',
            field=models.CharField(blank=True, help_text='Specialization from OAuth provider', max_length=255, verbose_name='OAuth Specialization'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_university',
            field=models.CharField(blank=True, help_text='University from OAuth provider', max_length=255, verbose_name='OAuth University'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Primary owner/administrator of the company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student profile that owns this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='accounts.studentprofile', verbose_name='Student'),
        ),
    ]
