# Generated by Django 5.2.7 on 2026-04-09 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_oauth_degree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyadditionalinfo',
            options={'verbose_name': 'Company Additional Information', 'verbose_name_plural': 'Companies Additional Information'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Current company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_position',
            field=models.CharField(blank=True, help_text='Current job position', max_length=255, verbose_name='Current Position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, help_text='Academic degree', max_length=100, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='desired_position',
            field=models.CharField(blank=True, help_text='Position the student is seeking', max_length=200, verbose_name='Desired Position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary', max_digits=12, null=True, verbose_name='Desired Salary'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, help_text='Bachelor, Master, PhD, etc.', max_length=100, verbose_name='Education Level'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise_areas',
            field=models.TextField(blank=True, help_text='Areas of expertise', verbose_name='Expertise Areas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook profile URL', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty or department', max_length=200, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL', verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Year of graduation or expected graduation', null=True, verbose_name='Graduation Year'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry sector', max_length=255, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='Whether this user is available as a mentor', verbose_name='Is Mentor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_open_to_opportunities',
            field=models.BooleanField(default=False, help_text='Whether open to new opportunities', verbose_name='Open to Opportunities'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether profile is visible to others', verbose_name='Is Visible'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='alumni_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, help_text='Professional field', max_length=255, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume/CV file', null=True, upload_to='resumes/', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_contact_info',
            field=models.BooleanField(default=False, help_text='Whether to show contact information', verbose_name='Show Contact Info'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, help_text='Field of study or specialization', max_length=200, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate')], default='student', help_text='Academic status of the user, either current student or graduate', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, help_text='University student identifier', max_length=50, verbose_name='Student ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter profile URL', verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or portfolio website', verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('remote', 'Remote')], help_text='Preferred work arrangement', max_length=50, verbose_name='Work Type'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of professional experience', null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, help_text='Telegram username', max_length=64, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('alumni', 'Alumni'), ('employer', 'Employer'), ('admin', 'Admin'), ('international_admin', 'International Admin'), ('main_admin', 'Main Admin')], default='guest', help_text='Type of user account (guest, student, employer, admin)', max_length=20, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student profile that owns this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
