# Generated by Django 5.2.7 on 2026-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_companyadditionalinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary company email address', max_length=254, null=True, verbose_name='Company Email'),
        ),
    ]
