# Generated by Django 5.2.7 on 2026-04-10 05:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course_year',
            field=models.CharField(blank=True, help_text='Academic course/year received from OAuth provider', max_length=20, verbose_name='Course Year'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's name received from OAuth provider", max_length=200, verbose_name="Father's Name"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gpa',
            field=models.FloatField(blank=True, help_text='Grade point average received from OAuth provider', null=True, verbose_name='GPA'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number received from OAuth provider', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills or competencies received from OAuth provider', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty_code',
            field=models.CharField(blank=True, help_text='Specialty code received from OAuth provider', max_length=100, verbose_name='Specialty Code'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, help_text='University name received from OAuth provider', max_length=255, verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('alumni', 'Alumni'), ('employer', 'Employer'), ('admin', 'Admin'), ('international_admin', 'International Admin'), ('main_admin', 'Main Admin')], db_index=True, default='student', help_text='Type of user account (guest, student, employer, admin)', max_length=20, verbose_name='User Type'),
        ),
    ]
