# Generated by Django 5.2.7 on 2026-04-11 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studentprofile_course_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(help_text='Primary owner/administrator of the company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
