# Generated by Django 5.2.7 on 2025-11-18 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the CV template', max_length=100, verbose_name='Template Name')),
                ('name_uz', models.CharField(help_text='Display name for the CV template', max_length=100, null=True, verbose_name='Template Name')),
                ('name_ru', models.CharField(help_text='Display name for the CV template', max_length=100, null=True, verbose_name='Template Name')),
                ('name_en', models.CharField(help_text='Display name for the CV template', max_length=100, null=True, verbose_name='Template Name')),
                ('thumbnail', models.ImageField(help_text='Preview image of the template', upload_to='cv_templates/', verbose_name='Thumbnail')),
                ('template_file', models.CharField(help_text='Path to the template file', max_length=100, verbose_name='Template File')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the template was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'CV Template',
                'verbose_name_plural': 'CV Templates',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, null=True, verbose_name='Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Current status of the resume', max_length=20, verbose_name='Status')),
                ('full_name', models.CharField(help_text='Complete name as it should appear on the resume', max_length=200, verbose_name='Full Name')),
                ('full_name_uz', models.CharField(help_text='Complete name as it should appear on the resume', max_length=200, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(help_text='Complete name as it should appear on the resume', max_length=200, null=True, verbose_name='Full Name')),
                ('full_name_en', models.CharField(help_text='Complete name as it should appear on the resume', max_length=200, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Professional email address', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, verbose_name='Phone')),
                ('location', models.CharField(help_text='City or location', max_length=100, verbose_name='Location')),
                ('location_uz', models.CharField(help_text='City or location', max_length=100, null=True, verbose_name='Location')),
                ('location_ru', models.CharField(help_text='City or location', max_length=100, null=True, verbose_name='Location')),
                ('location_en', models.CharField(help_text='City or location', max_length=100, null=True, verbose_name='Location')),
                ('salary_expectation', models.IntegerField(blank=True, help_text='Expected salary range', null=True, verbose_name='Salary Expectation')),
                ('summary', models.TextField(help_text='Professional summary or objective', verbose_name='Summary')),
                ('summary_uz', models.TextField(help_text='Professional summary or objective', null=True, verbose_name='Summary')),
                ('summary_ru', models.TextField(help_text='Professional summary or objective', null=True, verbose_name='Summary')),
                ('summary_en', models.TextField(help_text='Professional summary or objective', null=True, verbose_name='Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the CV was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update to the CV', verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='User who owns this CV', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('template', models.ForeignKey(blank=True, help_text='CV template used for this resume', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvbuilder.cvtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Name of the educational institution', max_length=200, verbose_name='Institution')),
                ('institution_uz', models.CharField(help_text='Name of the educational institution', max_length=200, null=True, verbose_name='Institution')),
                ('institution_ru', models.CharField(help_text='Name of the educational institution', max_length=200, null=True, verbose_name='Institution')),
                ('institution_en', models.CharField(help_text='Name of the educational institution', max_length=200, null=True, verbose_name='Institution')),
                ('degree', models.CharField(choices=[('secondary', 'Secondary Education'), ('specialized_secondary', 'Specialized Secondary'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('doctor', 'Doctorate')], help_text='Level of education achieved', max_length=50, verbose_name='Degree')),
                ('field_of_study', models.CharField(help_text='Major or field of specialization', max_length=100, verbose_name='Field of Study')),
                ('field_of_study_uz', models.CharField(help_text='Major or field of specialization', max_length=100, null=True, verbose_name='Field of Study')),
                ('field_of_study_ru', models.CharField(help_text='Major or field of specialization', max_length=100, null=True, verbose_name='Field of Study')),
                ('field_of_study_en', models.CharField(help_text='Major or field of specialization', max_length=100, null=True, verbose_name='Field of Study')),
                ('graduation_year', models.IntegerField(help_text='Year of graduation or completion', verbose_name='Graduation Year')),
                ('cv', models.ForeignKey(help_text='CV this education belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cvbuilder.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Name of the company or organization', max_length=200, verbose_name='Company')),
                ('company_uz', models.CharField(help_text='Name of the company or organization', max_length=200, null=True, verbose_name='Company')),
                ('company_ru', models.CharField(help_text='Name of the company or organization', max_length=200, null=True, verbose_name='Company')),
                ('company_en', models.CharField(help_text='Name of the company or organization', max_length=200, null=True, verbose_name='Company')),
                ('position', models.CharField(help_text='Job title or position held', max_length=200, verbose_name='Position')),
                ('position_uz', models.CharField(help_text='Job title or position held', max_length=200, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(help_text='Job title or position held', max_length=200, null=True, verbose_name='Position')),
                ('position_en', models.CharField(help_text='Job title or position held', max_length=200, null=True, verbose_name='Position')),
                ('start_date', models.DateField(help_text='When you started this position', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='When you left this position (leave blank if current)', null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is your current job', verbose_name='Current Position')),
                ('description', models.TextField(help_text='Responsibilities, achievements, and key accomplishments', verbose_name='Description')),
                ('description_uz', models.TextField(help_text='Responsibilities, achievements, and key accomplishments', null=True, verbose_name='Description')),
                ('description_ru', models.TextField(help_text='Responsibilities, achievements, and key accomplishments', null=True, verbose_name='Description')),
                ('description_en', models.TextField(help_text='Responsibilities, achievements, and key accomplishments', null=True, verbose_name='Description')),
                ('cv', models.ForeignKey(help_text='CV this experience belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cvbuilder.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the language', max_length=50, verbose_name='Language')),
                ('name_uz', models.CharField(help_text='Name of the language', max_length=50, null=True, verbose_name='Language')),
                ('name_ru', models.CharField(help_text='Name of the language', max_length=50, null=True, verbose_name='Language')),
                ('name_en', models.CharField(help_text='Name of the language', max_length=50, null=True, verbose_name='Language')),
                ('level', models.CharField(choices=[('a1', 'A1 - Beginner'), ('a2', 'A2 - Elementary'), ('b1', 'B1 - Intermediate'), ('b2', 'B2 - Upper Intermediate'), ('c1', 'C1 - Advanced'), ('c2', 'C2 - Proficient'), ('native', 'Native')], help_text='Your level of proficiency in this language', max_length=20, verbose_name='Proficiency Level')),
                ('cv', models.ForeignKey(help_text='CV this language belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cvbuilder.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill or technology', max_length=100, verbose_name='Skill Name')),
                ('name_uz', models.CharField(help_text='Name of the skill or technology', max_length=100, null=True, verbose_name='Skill Name')),
                ('name_ru', models.CharField(help_text='Name of the skill or technology', max_length=100, null=True, verbose_name='Skill Name')),
                ('name_en', models.CharField(help_text='Name of the skill or technology', max_length=100, null=True, verbose_name='Skill Name')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Your level of expertise in this skill', max_length=20, verbose_name='Proficiency Level')),
                ('cv', models.ForeignKey(help_text='CV this skill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvbuilder.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
