# Generated by Django 5.2.7 on 2025-10-28 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('thumbnail', models.ImageField(upload_to='cv_templates/', verbose_name='Превью')),
                ('template_file', models.CharField(max_length=100, verbose_name='Файл шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон резюме',
                'verbose_name_plural': 'Шаблоны резюме',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название резюме')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cv_photos/', verbose_name='Фото')),
                ('summary', models.TextField(blank=True, verbose_name='О себе')),
                ('show_photo', models.BooleanField(default=True, verbose_name='Показывать фото')),
                ('show_email', models.BooleanField(default=True, verbose_name='Показывать email')),
                ('show_phone', models.BooleanField(default=True, verbose_name='Показывать телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvbuilder.cvtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Организация')),
                ('issue_date', models.DateField(verbose_name='Дата получения')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID сертификата')),
                ('credential_url', models.URLField(blank=True, verbose_name='Ссылка на сертификат')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cvbuilder.cv')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CVSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default='Arial', max_length=50, verbose_name='Шрифт')),
                ('font_size', models.IntegerField(default=12, verbose_name='Размер шрифта')),
                ('primary_color', models.CharField(default='#2c3e50', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#3498db', max_length=7, verbose_name='Вторичный цвет')),
                ('margin', models.IntegerField(default=20, verbose_name='Отступы')),
                ('line_spacing', models.DecimalField(decimal_places=1, default=1.2, max_digits=3, verbose_name='Межстрочный интервал')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='cvbuilder.cv')),
            ],
            options={
                'verbose_name': 'Настройка резюме',
                'verbose_name_plural': 'Настройки резюме',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('degree', models.CharField(max_length=100, verbose_name='Степень')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Специальность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='По настоящее время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cvbuilder.cv')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='По настоящее время')),
                ('description', models.TextField(verbose_name='Описание обязанностей')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cvbuilder.cv')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык')),
                ('level', models.CharField(choices=[('a1', 'A1 - Начальный'), ('a2', 'A2 - Элементарный'), ('b1', 'B1 - Средний'), ('b2', 'B2 - Выше среднего'), ('c1', 'C1 - Продвинутый'), ('c2', 'C2 - Владение в совершенстве'), ('native', 'Родной')], max_length=20, verbose_name='Уровень')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cvbuilder.cv')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('technologies', models.CharField(max_length=300, verbose_name='Технологии')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на проект')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий проект')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cvbuilder.cv')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], max_length=20, verbose_name='Уровень')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='Лет опыта')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvbuilder.cv')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
