# Generated by Django 5.2.7 on 2026-01-28 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cvbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of certificate or certification', max_length=200, verbose_name='Certificate Name')),
                ('issuing_organization', models.CharField(help_text='Organization that issued the certificate', max_length=200, verbose_name='Issuing Organization')),
                ('issue_date', models.DateField(help_text='Date when certificate was issued', verbose_name='Issue Date')),
                ('expiration_date', models.DateField(blank=True, help_text='Date when certificate expires (if applicable)', null=True, verbose_name='Expiration Date')),
                ('certificate_id', models.CharField(blank=True, help_text='Certificate identification number', max_length=100, null=True, verbose_name='Certificate ID')),
                ('certificate_url', models.URLField(blank=True, help_text='Link to verify certificate online', null=True, verbose_name='Verification URL')),
                ('description', models.TextField(blank=True, help_text='Skills or knowledge acquired', null=True, verbose_name='Description')),
                ('certificate_file', models.FileField(blank=True, help_text='Upload scanned certificate (PDF, JPG, PNG)', null=True, upload_to='certificates/', verbose_name='Certificate File')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=200, verbose_name='Project Name')),
                ('role', models.CharField(help_text='Your role in the project', max_length=100, verbose_name='Your Role')),
                ('description', models.TextField(help_text='Brief description of the project', verbose_name='Project Description')),
                ('technologies', models.CharField(help_text='Technologies and tools used in the project', max_length=300, verbose_name='Technologies Used')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('project_url', models.URLField(blank=True, help_text='Link to live project or repository', null=True, verbose_name='Project URL')),
                ('is_personal', models.BooleanField(default=False, help_text='Is this a personal project?', verbose_name='Personal Project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the reference', max_length=200, verbose_name='Reference Name')),
                ('position', models.CharField(help_text='Position of the reference', max_length=200, verbose_name='Position')),
                ('company', models.CharField(help_text='Company where reference works', max_length=200, verbose_name='Company')),
                ('email', models.EmailField(help_text='Email address of the reference', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Phone number of the reference', max_length=20, verbose_name='Phone')),
                ('relationship', models.CharField(help_text='Your relationship with the reference', max_length=100, verbose_name='Relationship')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='cvtemplate',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'CV Template', 'verbose_name_plural': 'CV Templates'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-graduation_year', '-start_year'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-is_native', 'level'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-years_of_experience'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='cv',
            name='location',
        ),
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.TextField(default=1, help_text='Complete residential address', verbose_name='Full Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth (DD.MM.YYYY)', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='cv',
            name='city',
            field=models.CharField(default=1, help_text='City of residence', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='CV ID'),
        ),
        migrations.AddField(
            model_name='cv',
            name='desired_position',
            field=models.CharField(default=1, help_text='Position you are applying for', max_length=200, verbose_name='Desired Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='driver_license',
            field=models.BooleanField(default=False, help_text="Do you have a driver's license?", verbose_name="Driver's License"),
        ),
        migrations.AddField(
            model_name='cv',
            name='driver_license_category',
            field=models.CharField(blank=True, help_text="Driver's license category (e.g., B, C)", max_length=10, null=True, verbose_name='License Category'),
        ),
        migrations.AddField(
            model_name='cv',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='cv',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Profile'),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='cv',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='cv',
            name='military_service',
            field=models.TextField(blank=True, help_text='Information about military service (for male candidates)', null=True, verbose_name='Military Service'),
        ),
        migrations.AddField(
            model_name='cv',
            name='nationality',
            field=models.CharField(default='Uzbekistan', help_text='Citizenship', max_length=100, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='cv',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Passport number (7 digits)', max_length=7, null=True, verbose_name='Passport Number'),
        ),
        migrations.AddField(
            model_name='cv',
            name='passport_series',
            field=models.CharField(blank=True, help_text='Passport series (e.g., AA)', max_length=2, null=True, verbose_name='Passport Series'),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Additional contact number', max_length=20, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AddField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, help_text='Professional photo (recommended size: 3x4 cm)', null=True, upload_to='cv_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='cv',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio Website'),
        ),
        migrations.AddField(
            model_name='cv',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published Date'),
        ),
        migrations.AddField(
            model_name='cv',
            name='region',
            field=models.CharField(default=1, help_text='Region of Uzbekistan (e.g., Tashkent, Samarkand)', max_length=100, verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='salary_currency',
            field=models.CharField(default='UZS', help_text='Currency code (UZS, USD, EUR)', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='cv',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax Identification Number (9 digits)', max_length=9, null=True, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='css_file',
            field=models.CharField(blank=True, help_text='Path to CSS file for styling', max_length=200, null=True, verbose_name='CSS File'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Template description and features', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Free Template'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='template_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('creative', 'Creative'), ('minimalist', 'Minimalist'), ('executive', 'Executive')], default='classic', max_length=20, verbose_name='Template Type'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cv_templates/thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text='Projects, thesis, or additional information', null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='education',
            name='diploma_number',
            field=models.CharField(blank=True, help_text='Diploma or certificate number', max_length=50, null=True, verbose_name='Diploma Number'),
        ),
        migrations.AddField(
            model_name='education',
            name='education_level',
            field=models.CharField(choices=[('secondary', 'Secondary Education'), ('specialized_secondary', 'Specialized Secondary'), ('incomplete_higher', 'Incomplete Higher'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('professional', 'Professional Training')], default=1, help_text='Level of education', max_length=50, verbose_name='Education Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty or department', max_length=150, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average', max_digits=3, null=True, verbose_name='GPA'),
        ),
        migrations.AddField(
            model_name='education',
            name='honors',
            field=models.CharField(blank=True, help_text='Honors, awards, or distinctions', max_length=100, null=True, verbose_name='Honors'),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(default=1, help_text='Year when studies began', verbose_name='Start Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, help_text='Specific achievements with measurable results', null=True, verbose_name='Key Achievements'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_location',
            field=models.CharField(blank=True, help_text='City and country of the company', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.CharField(blank=True, help_text='Technologies, tools, and methodologies used', max_length=300, null=True, verbose_name='Technologies Used'),
        ),
        migrations.AddField(
            model_name='language',
            name='certificate_score',
            field=models.CharField(blank=True, help_text='Test score (e.g., IELTS 7.5, TOEFL 100)', max_length=10, null=True, verbose_name='Certificate Score'),
        ),
        migrations.AddField(
            model_name='language',
            name='certificate_type',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('cefr', 'CEFR Certificate'), ('none', 'No Certificate')], default='none', help_text='Language proficiency certificate', max_length=20, verbose_name='Certificate Type'),
        ),
        migrations.AddField(
            model_name='language',
            name='is_native',
            field=models.BooleanField(default=False, help_text='Is this your native language?', verbose_name='Native Language'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='general', help_text='Skill category (e.g., technical, soft, language)', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Examples of how you used this skill', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='last_used',
            field=models.IntegerField(blank=True, help_text='Year when you last used this skill professionally', null=True, verbose_name='Last Used'),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Number of years using this skill', null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(help_text='Professional email address', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='phone',
            field=models.CharField(help_text='Contact phone number in format: +998 XX XXX XX XX', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='salary_expectation',
            field=models.BigIntegerField(blank=True, help_text='Expected salary in UZS', null=True, verbose_name='Salary Expectation'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current status of the resume', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='summary',
            field=models.TextField(help_text='Brief professional summary and career objectives', verbose_name='Professional Summary'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, verbose_name='Resume Title'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(help_text='User who owns this CV', on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='accounts.studentprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='template_file',
            field=models.CharField(blank=True, help_text='Path to template file', max_length=200, null=True, verbose_name='Template File'),
        ),
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='Name of the degree or diploma', max_length=100, verbose_name='Degree/Diploma'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(help_text='Your major or specialty', max_length=100, verbose_name='Field of Study/Specialty'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Year of graduation', null=True, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='Name of university, college, or school', max_length=255, verbose_name='Educational Institution'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(help_text='Name of the company or organization', max_length=200, verbose_name='Company/Organization'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Key responsibilities, achievements, and skills used', verbose_name='Responsibilities and Achievements'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='When you left this position', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Your proficiency level in this skill', max_length=20, verbose_name='Proficiency Level'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Name of the skill', max_length=100, verbose_name='Skill Name'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['status', 'user'], name='cvbuilder_c_status_330557_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['created_at'], name='cvbuilder_c_created_f32532_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['cv', 'start_date'], name='cvbuilder_e_cv_id_dd69da_idx'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='reference',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='cvbuilder.cv', verbose_name='CV'),
        ),
    ]
