# Generated by Django 5.2.7 on 2025-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='full_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='cv',
            name='location_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='cv',
            name='location_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='cv',
            name='location_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary_en',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary_ru',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary_uz',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='cv',
            name='title_en',
            field=models.CharField(default='Мое резюме', max_length=200, null=True, verbose_name='Название резюме'),
        ),
        migrations.AddField(
            model_name='cv',
            name='title_ru',
            field=models.CharField(default='Мое резюме', max_length=200, null=True, verbose_name='Название резюме'),
        ),
        migrations.AddField(
            model_name='cv',
            name='title_uz',
            field=models.CharField(default='Мое резюме', max_length=200, null=True, verbose_name='Название резюме'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название шаблона'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название шаблона'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название шаблона'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Обязанности и достижения'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Обязанности и достижения'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Обязанности и достижения'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Навык'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Навык'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Навык'),
        ),
    ]
