# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0002_remove_cv_full_name_en_remove_cv_full_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='full_name_en',
            field=models.CharField(help_text='Complete name as it should appear on the resume', max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name_ru',
            field=models.CharField(help_text='Complete name as it should appear on the resume', max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name_uz',
            field=models.CharField(help_text='Complete name as it should appear on the resume', max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='cv',
            name='location_en',
            field=models.CharField(help_text='City or location', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='cv',
            name='location_ru',
            field=models.CharField(help_text='City or location', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='cv',
            name='location_uz',
            field=models.CharField(help_text='City or location', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary_en',
            field=models.TextField(help_text='Professional summary or objective', null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary_ru',
            field=models.TextField(help_text='Professional summary or objective', null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary_uz',
            field=models.TextField(help_text='Professional summary or objective', null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='cv',
            name='title_en',
            field=models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cv',
            name='title_ru',
            field=models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cv',
            name='title_uz',
            field=models.CharField(default='My Resume', help_text='Title or name of the resume', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='name_en',
            field=models.CharField(help_text='Display name for the CV template', max_length=100, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='name_ru',
            field=models.CharField(help_text='Display name for the CV template', max_length=100, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='name_uz',
            field=models.CharField(help_text='Display name for the CV template', max_length=100, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_en',
            field=models.CharField(help_text='Major or field of specialization', max_length=100, null=True, verbose_name='Field of Study'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_ru',
            field=models.CharField(help_text='Major or field of specialization', max_length=100, null=True, verbose_name='Field of Study'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_uz',
            field=models.CharField(help_text='Major or field of specialization', max_length=100, null=True, verbose_name='Field of Study'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(help_text='Name of the educational institution', max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_ru',
            field=models.CharField(help_text='Name of the educational institution', max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_uz',
            field=models.CharField(help_text='Name of the educational institution', max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(help_text='Name of the company or organization', max_length=200, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_ru',
            field=models.CharField(help_text='Name of the company or organization', max_length=200, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_uz',
            field=models.CharField(help_text='Name of the company or organization', max_length=200, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(help_text='Responsibilities, achievements, and key accomplishments', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ru',
            field=models.TextField(help_text='Responsibilities, achievements, and key accomplishments', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_uz',
            field=models.TextField(help_text='Responsibilities, achievements, and key accomplishments', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(help_text='Job title or position held', max_length=200, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_ru',
            field=models.CharField(help_text='Job title or position held', max_length=200, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_uz',
            field=models.CharField(help_text='Job title or position held', max_length=200, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(help_text='Name of the language', max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(help_text='Name of the language', max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(help_text='Name of the language', max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(help_text='Name of the skill or technology', max_length=100, null=True, verbose_name='Skill Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(help_text='Name of the skill or technology', max_length=100, null=True, verbose_name='Skill Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(help_text='Name of the skill or technology', max_length=100, null=True, verbose_name='Skill Name'),
        ),
    ]
