# Generated by Django 5.2.7 on 2026-01-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0002_certificate_project_reference_alter_cv_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='region',
            field=models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Fergana', 'Fergana'), ('Andijan', 'Andijan'), ('Namangan', 'Namangan'), ('Khorezm', 'Khorezm'), ('Kashkadarya', 'Kashkadarya'), ('Surkhandarya', 'Surkhandarya'), ('Jizzakh', 'Jizzakh'), ('Sirdarya', 'Sirdarya'), ('Navoi', 'Navoi'), ('Gulistan', 'Gulistan'), ('Qarshi', 'Qarshi'), ('Urganch', 'Urganch')], help_text='Region of Uzbekistan (e.g., Tashkent, Samarkand)', max_length=100, verbose_name='Region'),
        ),
    ]
