# Generated by Django 5.2.7 on 2026-02-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0003_alter_cv_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvtemplate',
            name='is_free',
        ),
    ]
