# Generated by Django 5.2.7 on 2026-02-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0004_remove_cvtemplate_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='passport_series',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='tin',
        ),
    ]
