# Generated by Django 5.2.7 on 2026-04-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_oauth_degree_and_more'),
        ('cvbuilder', '0005_remove_cv_passport_number_remove_cv_passport_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this CV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='accounts.studentprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(blank=True, help_text='CV this experience belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='language',
            name='cv',
            field=models.ForeignKey(blank=True, help_text='CV this language belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='cvbuilder.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='cvbuilder.cv', verbose_name='CV'),
        ),
    ]
