# Generated by Django 5.2.7 on 2026-04-09 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0006_alter_certificate_cv_alter_cv_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this CV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
