# Generated by Django 5.2.7 on 2025-11-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource category', max_length=100, verbose_name='Category Name')),
                ('name_uz', models.CharField(help_text='Name of the resource category', max_length=100, null=True, verbose_name='Category Name')),
                ('name_ru', models.CharField(help_text='Name of the resource category', max_length=100, null=True, verbose_name='Category Name')),
                ('name_en', models.CharField(help_text='Name of the resource category', max_length=100, null=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the educational resource', max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(help_text='Title of the educational resource', max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Title of the educational resource', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Title of the educational resource', max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the resource content', verbose_name='Description')),
                ('description_uz', models.TextField(help_text='Detailed description of the resource content', null=True, verbose_name='Description')),
                ('description_ru', models.TextField(help_text='Detailed description of the resource content', null=True, verbose_name='Description')),
                ('description_en', models.TextField(help_text='Detailed description of the resource content', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Optional image representing the resource', null=True, upload_to='resources/images/%Y/%m/%d/', verbose_name='Image')),
                ('url_youtube', models.URLField(blank=True, help_text='YouTube video URL if applicable', verbose_name='YouTube URL')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this resource is publicly visible', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(help_text='Category this resource belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
