# Generated by Django 5.2.7 on 2025-11-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecategory',
            name='created_at',
        ),
    ]
