# Generated by Django 5.2.7 on 2025-11-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='name_uz',
        ),
    ]
