# Generated by Django 5.2.7 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description_en',
            field=models.TextField(help_text='Detailed description of the resource content', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_ru',
            field=models.TextField(help_text='Detailed description of the resource content', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_uz',
            field=models.TextField(help_text='Detailed description of the resource content', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_en',
            field=models.CharField(help_text='Title of the educational resource', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_ru',
            field=models.CharField(help_text='Title of the educational resource', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_uz',
            field=models.CharField(help_text='Title of the educational resource', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='description_en',
            field=models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='name_en',
            field=models.CharField(help_text='Name of the resource category', max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='name_ru',
            field=models.CharField(help_text='Name of the resource category', max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='name_uz',
            field=models.CharField(help_text='Name of the resource category', max_length=100, null=True, verbose_name='Category Name'),
        ),
    ]
